### ISSUE TITLE
Profile Updates

### ISSUE THREAD

**Issue by bruce-ones-zeros** [Paul-Myles/paul-myles.github.io#10]
Currently Tom appears for scores between 23-26 points

Please replace with Josh Moore

**Comment by Paul-Myles** [comment]
Is Josh the one with the kid on his shoulders?

**Comment by bruce-ones-zeros** [comment]
just about to email you 3 new pictures for Josh Moore

**Comment by bruce-ones-zeros** [comment]
but yes - that is the right picture
