### ISSUE TITLE
Remove scale for results

### ISSUE THREAD

**Issue by bruce-ones-zeros** [Paul-Myles/paul-myles.github.io#2]
Please remove these graphics. Site should go from end of intro copy into question 1 open

![screen shot 2015-03-02 at 1 34 17 pm](https://cloud.githubusercontent.com/assets/2859184/6434195/68ffe874-c0e8-11e4-9314-6d280488c138.png)

**Comment by Paul-Myles** [comment]
Did you want question 1 to be already opened when the page is loaded?

**Comment by bruce-ones-zeros** [comment]
yes - i think that would work best
