### ISSUE TITLE
results screen not showing image montage

### ISSUE THREAD

**Issue by bruce-ones-zeros** [Paul-Myles/paul-myles.github.io#5]
The results page is supposed to show a montage of staff pick as per this layout:

![bootstrap3-1170px 3](https://cloud.githubusercontent.com/assets/2859184/6434354/b98a4818-c0eb-11e4-9408-61ce8ead2a73.jpg)

**Comment by Paul-Myles** [comment]
What URL are you viewing the results page on?
http://paul-myles.github.io/ or locally?

**Comment by bruce-ones-zeros** [comment]
http://paul-myles.github.io/

**Comment by Paul-Myles** [comment]
Do you guys have a FTP I can connect to to see if it works there?
Just because it shows up on my local but not on Github for some reason.

**Comment by bruce-ones-zeros** [comment]
ftp.mydns.net.nz
yrtravelbuddies

will email password

**Comment by Paul-Myles** [comment]
Never mind I found what the issue was.
Some of the photos taken were on Smartphones which I believe embed Geo-Location coordinates into the images which doubled their file size and Github wasn't liking the Geo-Location stuff.
